In [1]:
import numpy as np
import pandas as pd

In [1]:
# df = pd.read_pickle('df_all_2.pkl')
# y = pd.read_pickle('resp.pkl')

In [3]:
# df.head()

In [34]:
df_train = df.loc[df['mod_lb'] == 'train', :].drop(['mod_lb'], axis = 1)
df_test = df.loc[df['mod_lb'] == 'test', :].drop(['mod_lb'], axis = 1)

In [2]:
# df_train.head()

In [36]:
df_train.select_dtypes(include = ['object']).columns

Index([], dtype='object')

In [4]:
# df_train.columns

In [38]:
# group sampling

In [39]:
from sklearn.model_selection import GroupKFold

folds_split = list(GroupKFold(n_splits = 5).split(X = df_train, y = y, groups = df_train.loc[:, 'incident_id']))

In [40]:
folds_split

[(array([     0,      1,      5, ..., 145060, 145061, 145062]),
  array([     2,      3,      4, ..., 145048, 145049, 145059])),
 (array([     0,      1,      2, ..., 145060, 145061, 145062]),
  array([    16,     17,     46, ..., 145056, 145057, 145058])),
 (array([     0,      1,      2, ..., 145058, 145059, 145060]),
  array([     7,      8,      9, ..., 145055, 145061, 145062])),
 (array([     2,      3,      4, ..., 145060, 145061, 145062]),
  array([     0,      1,      5, ..., 145034, 145035, 145036])),
 (array([     0,      1,      2, ..., 145059, 145061, 145062]),
  array([    30,     32,     33, ..., 145051, 145052, 145060]))]

In [41]:
df_train.drop(['row_id', 'incident_id', 'vehicle_id', 'occupant_id'], axis = 1, inplace = True)

In [63]:
df_test.drop(['row_id', 'incident_id', 'vehicle_id', 'occupant_id'], axis = 1, inplace = True)

In [5]:
# df_train.head()

In [6]:
# df_test.head()

In [7]:
# check missing value rate
# for col in df_test.columns:
#     print('column name: ', col)
#     print(df_test[col].isnull().sum()/len(df_test))

In [75]:
# impute missing values

for col in df_test.columns:
    df_test[col].fillna(df_test[col].median(), inplace = True)

In [8]:
# for col in df_test.columns:
#     print('column name: ', col)
#     print(df_test[col].isnull().sum()/len(df_test))

In [42]:
import lightgbm as lgb

In [43]:
# lgb_data = lgb.Dataset(df_train, label = y, 
#                        feature_name = ['total_veh_in_inc', 'total_occ_in_inc', 'total_occ_in_veh',
#        'actual_veh_in_inc', 'actual_per_in_inc', 'actual_occ_in_veh',
#        'actual_ped', 'inc_day', 'inc_region', 'inc_daylight', 'inc_weather',
#        'veh_roadcond', 'veh_roadslope', 'veh_lanes', 'veh_lanediv',
#        'veh_speedlim', 'occ_age', 'occ_sex', 'occ_role', 'occ_position',
#        'occ_seatbelt', 'occ_airbag', 'occ_alcohol', 'veh_owner', 'veh_type',
#        'veh_style', 'veh_weight', 'veh_manu', 'veh_doors', 'veh_wheels',
#        'veh_drive', 'veh_fuel', 'veh_eng1', 'veh_eng2', 'veh_trailer',
#        'drv_height', 'drv_weight', 'drv_licence', 'drv_status', 'drv_crash',
#        'drv_pts', 'drv_dui', 'drv_spd', 'drv_alcohol', 'inc_type',
#        'inc_speeding', 'veh_speed', 'veh_braking', 'veh_stability',
#        'veh_movement', 'veh_impact', 'inc_descrip', 'veh_descrip',
#        'veh_damage', 'veh_age_new', 'drv_ban1_new', 'drv_ban2_new',
#        'inc_month_new', 'inc_hour_new', 'veh_inc_maxage'],
#                        categorical_feature = ['inc_day', 'inc_daylight', 'inc_weather', 'veh_roadcond',
#        'veh_roadslope', 'veh_lanediv', 'occ_sex', 'occ_role', 'occ_position',
#        'occ_seatbelt', 'occ_airbag', 'occ_alcohol', 'veh_owner', 'veh_type',
#        'veh_style', 'veh_weight', 'veh_manu', 'veh_drive', 'veh_fuel',
#        'veh_trailer', 'drv_licence', 'drv_status', 'drv_alcohol', 'inc_type',
#        'inc_speeding', 'veh_braking', 'veh_stability', 'veh_movement',
#         'veh_impact', 'inc_descrip', 'veh_descrip', 'veh_damage'])

In [65]:
lgb_data = lgb.Dataset(df_train, label = y)

In [66]:
lgb_test = lgb.Dataset(df_test)

In [56]:
params = {'num_leaves': 10,
         'max_depth': 5}

In [70]:
mod_1 = lgb.cv(params = params,
               num_boost_round = 1000,
               verbose_eval = 200,
               train_set = lgb_data,
               #early_stopping_rounds = 200,
               folds = folds_split)

In [80]:
mod_2 = lgb.train(params = params,
                 num_boost_round = 1000,
                 verbose_eval = 200,
                 train_set = lgb_data,
                 #folds = folds_split)

TypeError: train() got an unexpected keyword argument 'folds'

In [79]:
mod_2

NameError: name 'mod_2' is not defined