In [1]:
import pandas as pd
import numpy as np

In [1]:
# df = pd.read_csv('pp_data_train.csv')
# print(df.shape)

In [2]:
# df.head(7)

In [3]:
# col_n1 = df.select_dtypes(include = ['object']).columns.values
# col_n2 = df.select_dtypes(exclude = ['object']).columns.values

# print(len(col_n1))
# print(col_n1)

# print(len(col_n2))
# print(col_n2)

In [4]:
# print(df.columns.values)

In [5]:
# for col in df.columns.values:
#     print('Column name: ', col)
#     print('Missing value counts: ', df[col].isnull().sum())
#     print('\n')

In [6]:
# inc_datetime

# df['inc_datetime'] = pd.to_datetime(df['inc_datetime'])
# df['inc_datetime']

In [33]:
df['inc_datetime'].isnull().sum()

571

In [34]:
df['inc_datetime'].isnull().astype(int).sum()

571

In [35]:
df['inc_datetime_isnull'] = df['inc_datetime'].isnull().astype(int)

In [36]:
df['inc_datetime_mon'] = df['inc_datetime'].dt.month
df['inc_datetime_hour'] = df['inc_datetime'].dt.hour

In [37]:
df['inc_datetime_hour'].isnull().sum()

571

In [38]:
# inc_day

df['inc_day'].isnull().sum()

0

In [39]:
df['inc_day'].value_counts()

Saturday     26513
Sunday       23405
Friday       22922
Thursday     19105
Monday       18115
Wednesday    17721
Tuesday      17282
Name: inc_day, dtype: int64

In [40]:
# inc_daylight

print(df['inc_daylight'].isnull().sum())

print(df['inc_daylight'].value_counts())

0
Daylight                     76665
Dark no streetlights         36531
Dark streetlights            24619
Dusk                          3489
Dawn                          2574
Dark unknown streetlights      779
unknown                        406
Name: inc_daylight, dtype: int64


In [7]:
# l_null = [1 if cat in ['unknown'] else 0 for cat in df['inc_daylight']]
# print(l_null)

In [42]:
sum(l_null)

406

In [43]:
df['inc_daylight_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['inc_daylight']]
df['inc_daylight_isnull'].head()

0    0
1    0
2    0
3    0
4    0
Name: inc_daylight_isnull, dtype: int64

In [44]:
df['inc_daylight_isnull'].sum()

406

In [45]:
# inc_weather

print(df['inc_weather'].isnull().sum())

print(df['inc_weather'].value_counts())

0
Clear          103145
Cloudy          22407
Rain            10067
unknown          4650
Snow             2048
Fog              1635
Sleet/Hail        619
Other             306
Heavy winds       186
Name: inc_weather, dtype: int64


In [46]:
df['inc_weather_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['inc_weather']]
df['inc_weather_isnull'].head()

0    0
1    0
2    0
3    0
4    0
Name: inc_weather_isnull, dtype: int64

In [47]:
df['inc_weather_isnull'].sum()

4650

In [48]:
# veh_roadcond

print(df['veh_roadcond'].isnull().sum())

print(df['veh_roadcond'].value_counts())

0
Dry                122122
Wet                 16083
Ice                  1798
Snow                 1761
unknown              1346
Not a road            860
Other                 562
Snow slush            323
Water (sitting)       208
Name: veh_roadcond, dtype: int64


In [50]:
df['veh_roadcond_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_roadcond']]

In [51]:
df['veh_roadcond_isnull'].head()

0    0
1    0
2    0
3    0
4    0
Name: veh_roadcond_isnull, dtype: int64

In [52]:
# veh_roadslope

print(df['veh_roadslope'].isnull().sum())
print(df['veh_roadslope'].value_counts())

0
Flat                  100091
Hill unknown slope     15264
unknown                10650
Downhill                8455
Uphill                  5922
Crest of hill           3347
Not a road               860
Bottom of Hill           474
Name: veh_roadslope, dtype: int64


In [54]:
df['veh_roadslope_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_roadslope']]
df['veh_roadslope_isnull'].head()

0    0
1    0
2    0
3    0
4    0
Name: veh_roadslope_isnull, dtype: int64

In [55]:
df['veh_roadslope_isnull'].sum()

10650

In [57]:
# veh_lanediv

print(df['veh_lanediv'].isnull().sum())
print(df['veh_lanediv'].value_counts())

0
2-way Not divided           82186
2-way Divided No barrier    26018
2-way Divided Barrier       23005
Entrance/Exit lane          10192
1-way                        1731
unknown                      1071
Not a road                    860
Name: veh_lanediv, dtype: int64


In [58]:
df['veh_lanediv_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_lanediv']]
df['veh_lanediv_isnull'].head()

0    0
1    0
2    0
3    0
4    0
Name: veh_lanediv_isnull, dtype: int64

In [59]:
# occ_sex

print(df['occ_sex'].isnull().sum())
print(df['occ_sex'].value_counts())

0
Male      95540
Female    49523
Name: occ_sex, dtype: int64


In [60]:
# occ_role

print(df['occ_role'].isnull().sum())
print(df['occ_role'].value_counts())

0
Driver            96541
Passenger         47951
Not-in-transit      571
Name: occ_role, dtype: int64


In [61]:
# occ_position

print(df['occ_position'].isnull().sum())
print(df['occ_position'].value_counts())

0
Front right side         96861
Front left side          24591
Second row right side     7588
Second row left side      7578
Second row middle         2660
Other enclosed            2087
unknown                   1056
Other unenclosed           506
Front middle               495
Rear right side            487
Rear left side             464
Second row other           279
Rear middle                265
Rear other                  76
Front other                 46
In towage                   24
Name: occ_position, dtype: int64


In [62]:
df['occ_position_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['occ_position']]

In [63]:
# occ_seatbelt

print(df['occ_seatbelt'].isnull().sum())
print(df['occ_seatbelt'].value_counts())

0
Shoulder & Lap Belt     82789
No seatbelt             36691
unknown                 13828
Helmet                   6870
Non-motorist             1389
Child Forward facing     1103
Lap Belt Only            1065
Child Booster seat        545
Shoulder Belt Only        404
Child Rear facing         379
Name: occ_seatbelt, dtype: int64


In [64]:
df['occ_seatbelt_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['occ_seatbelt']]
print(df['occ_seatbelt_isnull'].sum())

13828


In [65]:
#occ_airbag

print(df['occ_airbag'].isnull().sum())
print(df['occ_airbag'].value_counts())

0
None deployed            58096
unknown                  32030
Front airbag deployed    31667
Other airbag deployed    23270
Name: occ_airbag, dtype: int64


In [67]:
df['occ_airbag_isnull'] = [1 if cat in  ['unknown'] else 0 for cat in df['occ_airbag']]

print(df['occ_airbag_isnull'].sum())

32030


In [68]:
# occ_alcohol

print(df['occ_alcohol'].isnull().sum())
print(df['occ_alcohol'].value_counts())

0
unknown    68474
No         62727
Yes        13862
Name: occ_alcohol, dtype: int64


In [69]:
df['occ_alcohol_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['occ_alcohol']]

print(df['occ_alcohol_isnull'].sum())

68474


In [70]:
# veh_owner

print(df['veh_owner'].isnull().sum())
print(df['veh_owner'].value_counts())

0
Driver                 77570
Other private owner    46048
Business vehicle       14703
unknown                 5046
Rental                  1361
Stolen                   335
Name: veh_owner, dtype: int64


In [72]:
df['veh_owner_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_owner']]
print(df['veh_owner_isnull'].sum())

5046


In [73]:
# veh_type

print(df['veh_type'].isnull().sum())
print(df['veh_type'].value_counts())

3298
Truck            75713
Passenger Car    54805
Motorcycle       11247
Name: veh_type, dtype: int64


In [8]:
# veh_style

# print(df['veh_style'].isnull().sum())
# print(df['veh_style'].value_counts(dropna = False))

In [76]:
isnull(np.nan)

NameError: name 'isnull' is not defined

In [78]:
np.isnan(np.nan)

True

In [82]:
l = [1 if cat in [np.nan] else 0 for cat in df['veh_style']]

In [83]:
sum(l)

3298

In [87]:
df['veh_style_isnull'] = [1 if cat in [np.nan] else 0 for cat in df['veh_style']]
print(df['veh_style_isnull'].sum())

3298


In [86]:
# veh_weight

print(df['veh_weight'].isnull().sum())
print(df['veh_weight'].value_counts(dropna  =False))

133408
NaN           133408
over 12T        9064
up to 12T       2484
up to 4.5T       107
Name: veh_weight, dtype: int64


In [88]:
df['veh_weight_isnull'] = [1 if cat in [np.nan] else 0 for cat in df['veh_weight']]
print(df['veh_weight_isnull'].sum())

133408


In [9]:
# veh_manu

# print(df['veh_manu'].isnull().sum())
# print(df['veh_manu'].value_counts(dropna = False))

In [91]:
df['veh_manu_isnull'] = [1 if cat in [np.nan] else 0 for cat in df['veh_manu']]

print(df['veh_manu_isnull'].sum())

6911


In [92]:
# veh_drive

print(df['veh_drive'].isnull().sum())
print(df['veh_drive'].value_counts(dropna = False))

0
Front Wheel Drive    57270
Rear Wheel Drive     40344
Rear w/4x4           22472
unknown              14796
Full wheel drive      9168
Front w/4x4           1013
Name: veh_drive, dtype: int64


In [93]:
df['veh_drive_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_drive']]

print(df['veh_drive_isnull'].sum())

14796


In [94]:
# veh_fuel

print(df['veh_fuel'].isnull().sum())
print(df['veh_fuel'].value_counts())

0
Petrol         104886
Diesel          14745
unknown         14681
Multiple         9549
Hybrid           1064
Natural Gas       107
Electric           31
Name: veh_fuel, dtype: int64


In [95]:
df['veh_fuel_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_fuel']]

print(df['veh_fuel_isnull'].sum())

14681


In [96]:
# veh_trailer

print(df['veh_trailer'].isnull().sum())
print(df['veh_trailer'].value_counts())

0
No trailer              137069
One trailer               7539
Two or more trailers       269
Towing other vehicle       186
Name: veh_trailer, dtype: int64


In [97]:
# drv_licence

print(df['drv_licence'].isnull().sum())
print(df['drv_licence'].value_counts())

0
Full          130518
No licence      8331
Non-full        4253
unknown         1961
Name: drv_licence, dtype: int64


In [98]:
df['drv_licence_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['drv_licence']]
print(df['drv_licence_isnull'].sum())

1961


In [100]:
# drv_status

print(df['drv_status'].isnull().sum())
print(df['drv_status'].value_counts(dropna = False))

571
Clean         122547
Penalised      10318
No licence      8331
Expired         1873
unknown         1423
NaN              571
Name: drv_status, dtype: int64


In [101]:
l = [1 if cat in ['unknown', np.nan] else 0 for cat in df['drv_status']]
sum(l)

1994

In [103]:
df['drv_status_isnull'] = [1 if cat in ['unknown', np.nan] else 0 for cat in df['drv_status']]

print(df['drv_status_isnull'].sum())

1994


In [10]:
# drv_ban1_mo

# print(df['drv_ban1_mo'].isnull().sum())
# print(df['drv_ban1_mo'].value_counts())

In [108]:
df['drv_ban1_mo_isnull'] = [1 if cat in ['No record', 'unknown'] else 0 for cat in df['drv_ban1_mo']]
print(df['drv_ban1_mo_isnull'].sum())

83987


In [109]:
encoding = {'Jan.': 1, 'Feb.': 2, 'Mar.': 3, 'Apr.': 4, 'May': 5, 'June': 6, 'July': 7, 'Aug.': 8,
           'Sept.': 9, 'Oct.': 10, 'Nov.': 11, 'Dec.': 12, 'No record': np.nan, 'unknown': np.nan}

df['drv_ban1_mo_num'] = df['drv_ban1_mo'].map(encoding)

print(df['drv_ban1_mo_num'].value_counts())

7.0     5406
3.0     5368
8.0     5328
10.0    5278
5.0     5218
9.0     5184
1.0     5031
6.0     5028
4.0     4885
2.0     4829
11.0    4789
12.0    4732
Name: drv_ban1_mo_num, dtype: int64


In [11]:
# drv_ban1_yr

# print(df['drv_ban1_yr'].isnull().sum())
# print(df['drv_ban1_yr'].value_counts(dropna = False))

In [112]:
df['drv_ban1_yr_isnull'] = [1 if cat in ['No record', 'unknown'] else 0 for cat in df['drv_ban1_yr']]
print(df['drv_ban1_yr_isnull'].sum())

83984


In [113]:
encoding = {'2007': 2007, '2008': 2008, '2009': 2009, '2010': 2010, '2011': 2011, '2012': 2012, '2013': 2013,
           '2014': 2014, 'No record': np.nan, 'unknown': np.nan}

df['drv_ban1_yr_num'] = df['drv_ban1_yr'].map(encoding)

print(df['drv_ban1_yr_num'].value_counts(dropna = False))

NaN        83984
 2009.0    13486
 2010.0    13458
 2011.0    10695
 2008.0     8414
 2012.0     7236
 2013.0     4329
 2007.0     2110
 2014.0     1351
Name: drv_ban1_yr_num, dtype: int64


In [114]:
# drv_ban2_mo

print(df['drv_ban2_mo'].isnull().sum())
print(df['drv_ban2_mo'].value_counts(dropna = False))

0
No record    81260
Aug.          5413
July          5384
May           5305
Mar.          5282
Oct.          5224
June          5216
Sept.         5063
Jan.          5061
Dec.          4909
Apr.          4877
Feb.          4686
Nov.          4659
unknown       2724
Name: drv_ban2_mo, dtype: int64


In [115]:
df['drv_ban2_mo_isnull'] = [1 if cat in ['No record', 'unknown'] else 0 for cat in df['drv_ban2_yr']]
print(df['drv_ban2_mo_isnull'].sum())

83983


In [116]:
encoding = {'Jan.': 1, 'Feb.': 2, 'Mar.': 3, 'Apr.': 4, 'May': 5, 'June': 6, 'July': 7, 'Aug.': 8,
           'Sept.': 9, 'Oct.': 10, 'Nov.': 11, 'Dec.': 12, 'No record': np.nan, 'unknown': np.nan}

df['drv_ban2_mo_num'] = df['drv_ban2_mo'].map(encoding)

print(df['drv_ban2_mo_num'].value_counts())

8.0     5413
7.0     5384
5.0     5305
3.0     5282
10.0    5224
6.0     5216
9.0     5063
1.0     5061
12.0    4909
4.0     4877
2.0     4686
11.0    4659
Name: drv_ban2_mo_num, dtype: int64


In [118]:
# drv_ban2_yr

print(df['drv_ban2_yr'].isnull().sum())
print(df['drv_ban2_yr'].value_counts(dropna = False))

0
No record    81260
2011         13908
2012         12148
2010         11195
2013          9218
2009          6956
2014          3957
2008          3088
unknown       2723
2007           610
Name: drv_ban2_yr, dtype: int64


In [119]:
df['drv_ban2_yr_isnull'] = [1 if cat in ['No record', 'unknown'] else 0 for cat in df['drv_ban2_yr']]
print(df['drv_ban2_yr_isnull'].sum())

83983


In [120]:
encoding = {'2007': 2007, '2008': 2008, '2009': 2009, '2010': 2010, '2011': 2011, '2012': 2012, '2013': 2013,
           '2014': 2014, 'No record': np.nan, 'unknown': np.nan}

df['drv_ban2_yr_num'] = df['drv_ban2_yr'].map(encoding)

print(df['drv_ban2_yr_num'].value_counts(dropna = False))

NaN        83983
 2011.0    13908
 2012.0    12148
 2010.0    11195
 2013.0     9218
 2009.0     6956
 2014.0     3957
 2008.0     3088
 2007.0      610
Name: drv_ban2_yr_num, dtype: int64


In [123]:
#drv_alcohol

print(df['drv_alcohol'].isnull().sum())
print(df['drv_alcohol'].value_counts(dropna = False))

0
No     118605
Yes     26458
Name: drv_alcohol, dtype: int64


In [125]:
# inc_type

print(df['inc_type'].isnull().sum())
print(df['inc_type'].value_counts(dropna = False))

0
Road departure                    22962
unknown                           22153
Head on collision                 16931
Impact pedestrian                 14205
Crossing paths                    13341
Road departure loss of control    11927
Side collision                    10933
Turning across path               10379
Turning into path                  6475
Rear ended slowed                  5026
Rear ended stationary              4381
Rear ended braking                 1744
Impact other                       1068
Rear ended other                   1038
Side collision changing lanes       781
Impact parked vehicle               531
Road departure avoid collision      412
Impact other frontal                325
Reversing                           251
Impact fixed object                 200
Name: inc_type, dtype: int64


In [126]:
df['inc_type_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['inc_type']]
print(df['inc_type_isnull'].sum())

22153


In [127]:
# inc_speeding

print(df['inc_speeding'].isnull().sum())
print(df['inc_speeding'].value_counts(dropna = False))

0
No         112985
Yes         26342
unknown      5736
Name: inc_speeding, dtype: int64


In [129]:
df['inc_speeding_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['inc_speeding']]
print(df['inc_speeding_isnull'].sum())

5736


In [130]:
# veh_braking

print(df['veh_braking'].isnull().sum())
print(df['veh_braking'].value_counts(dropna = False))

0
unknown                 73000
No maneuver             43539
Swerving                14052
Braking                  8163
Braking and Swerving     4323
Other                    1365
Accelerating              370
No Driver                 138
Releasing brakes          113
Name: veh_braking, dtype: int64


In [131]:
df['veh_braking_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_braking']]
print(df['veh_braking_isnull'].sum())

73000


In [133]:
# veh_stability

print(df['veh_stability'].isnull().sum())
print(df['veh_stability'].value_counts(dropna = False))

0
Wheel misalignment       82715
unknown                  47087
Skidding with twist       8860
Skidding                  5995
Other loss of control      306
No Driver                  100
Name: veh_stability, dtype: int64


In [134]:
df['veh_stability_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_stability']]
print(df['veh_stability_isnull'].sum())

47087


In [135]:
# veh_movement

print(df['veh_movement'].isnull().sum())
print(df['veh_movement'].value_counts(dropna = True))

0
Stayed in lane                 60314
unknown                        38653
Departed road                  29698
Departed lane                  12364
Other movement                  2226
Stayed on road unknown lane     1708
No Driver                        100
Name: veh_movement, dtype: int64


In [136]:
df['veh_movement_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_movement']]
print(df['veh_movement_isnull'].sum())

38653


In [137]:
# veh_impact

print(df['veh_impact'].isnull().sum())
print(df['veh_impact'].value_counts())

0
Head on              74922
Not a collision      11182
Rear end              9948
Side right            9343
Side left             8089
Front 30deg right     5621
unknown               5452
Front 30deg left      4990
Front 60deg right     3497
Front 60deg left      3198
Other area            2336
Back 60deg right      1880
Back 60deg left       1726
Back 30deg right      1427
Back 30deg left       1284
Object impact          168
Name: veh_impact, dtype: int64


In [139]:
df['veh_impact_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_impact']]

print(df['veh_impact_isnull'].sum())

5452


In [140]:
# inc_descrip

print(df['inc_descrip'].isnull().sum())
print(df['inc_descrip'].value_counts())

0
Collision with in-transit vehicle    82911
Collision with lifeform              16338
Collision with object                15434
Non-roadway                          11750
Instability                          10597
Collision with safety barrier         4853
Collision with parked vehicle         1557
Dynamic                               1220
Hit by other vehicle                   153
Non-collision                          140
Pothole                                 76
unknown                                 34
Name: inc_descrip, dtype: int64


In [142]:
df['inc_descrip_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['inc_descrip']]
print(df['inc_descrip_isnull'].sum())

34


In [143]:
# veh_descrip

print(df['veh_descrip'].isnull().sum())
print(df['veh_descrip'].value_counts())

0
Collision with in-transit vehicle    81566
Instability                          19065
Collision with lifeform              16278
Collision with object                15859
Non-roadway                           3546
Dynamic                               2938
Collision with safety barrier         2532
Hit by other vehicle                  1603
Collision with parked vehicle          948
unknown                                635
Non-collision                           83
Pothole                                 10
Name: veh_descrip, dtype: int64


In [145]:
df['veh_descrip_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_descrip']]
print(df['veh_descrip_isnull'].sum())

635


In [146]:
# veh_damage

print(df['veh_damage'].isnull().sum())
print(df['veh_damage'].value_counts())

0
Disabling    109296
Moderate      13770
Minor         10132
unknown        9400
No damage      2465
Name: veh_damage, dtype: int64


In [147]:
df['veh_damage_isnull'] = [1 if cat in ['unknown'] else 0 for cat in df['veh_damage']]
print(df['veh_damage_isnull'].sum())

9400


In [148]:
# numerical features

In [149]:
# total_veh_in_inc

df['total_veh_in_inc'].isnull().sum()

0

In [150]:
sum(df['total_veh_in_inc'] == -1)

0

In [152]:
# total_occ_in_inc

df['total_occ_in_veh'].isnull().sum()

0

In [153]:
sum(df['total_occ_in_veh'] == -1)

0

In [154]:
# actual_veh_in_inc

df['actual_veh_in_inc'].isnull().sum()

0

In [156]:
sum(df['actual_veh_in_inc'] == -1)

0

In [157]:
# actual_per_in_inc

df['actual_per_in_inc'].isnull().sum()

0

In [158]:
sum(df['actual_per_in_inc'] == -1)

0

In [159]:
# actual_occ_in_veh

df['actual_occ_in_veh'].isnull().sum()

0

In [160]:
sum(df['actual_occ_in_veh'] == -1)

0

In [161]:
# actual_ped

df['actual_ped'].isnull().sum()

0

In [162]:
sum(df['actual_ped'] == -1)

0

In [163]:
# inc_region

df['inc_region'].head()

0    48
1    48
2     6
3     6
4     6
Name: inc_region, dtype: int64

In [164]:
df['inc_region'].isnull().sum()

0

In [165]:
sum(df['inc_region'] == -1)

0

In [166]:
# veh_lanes

df['veh_lanes'].isnull().sum()

0

In [167]:
sum(df['veh_lanes'] == -1)

1402

In [169]:
l = [1 if num == -1 else 0 for num in df['veh_lanes']]
print(sum(l))
print(l[:5])

1402
[0, 0, 0, 0, 0]


In [171]:
df['veh_lanes_isnull'] = [1 if num == -1 else 0 for num in df['veh_lanes']]

In [172]:
# veh_speedlim

print(df['veh_speedlim'].isnull().sum())

0


In [173]:
sum(df['veh_speedlim'] == -1)

5383

In [174]:
df['veh_speedlim_isnull'] = [1 if num == -1 else 0 for num in df['veh_speedlim']]

In [175]:
sum(df['veh_speedlim_isnull'])

5383

In [176]:
#occ_age

df['occ_age'].isnull().sum()

0

In [177]:
sum(df['occ_age'] == -1)

577

In [180]:
df['occ_age_isnull'] = [1 if num == -1 else 0 for num in df['occ_age']]

In [181]:
sum(df['occ_age_isnull'])

577

In [183]:
#veh_age

df['veh_year'].isnull().sum()

0

In [184]:
sum(df['veh_year'] == -1)

758

In [186]:
df['veh_year_isnull'] = [1 if num == -1 else 0 for num in df['veh_year']]

print(sum(df['veh_year_isnull']))

758


In [187]:
# veh_doors

df['veh_doors'].isnull().sum()

0

In [188]:
sum(df['veh_doors'] == -1)

3298

In [190]:
df['veh_doors_isnull'] = [1 if num == -1 else 0 for num in df['veh_doors']]

print(sum(df['veh_doors_isnull']))

3298


In [191]:
#veh_wheels

print(df['veh_wheels'].isnull().sum())
print(sum(df['veh_wheels'] == -1))

0
47927


In [192]:
df['veh_wheels_isnull'] = [1 if num == -1 else 0 for num in df['veh_wheels']]
print(sum(df['veh_wheels_isnull']))

47927


In [194]:
# veh_eng1

print(df['veh_eng1'].isnull().sum())
print(sum(df['veh_eng1'] == -1))

0
18435


In [195]:
df['veh_eng1_isnull'] = [1 if num == -1 else 0 for num in df['veh_eng1']]

print(sum(df['veh_eng1_isnull']))

18435


In [196]:
#veh_eng2

print(df['veh_eng2'].isnull().sum())
print(sum(df['veh_eng2'] == -1))

0
3617


In [197]:
df['veh_eng2_isnull'] = [1 if num == -1 else 0 for num in df['veh_eng2']]

print(sum(df['veh_eng2_isnull']))

3617


In [198]:
# drv_height

print(df['drv_height'].isnull().sum())
print(sum(df['drv_height'] == -1))

0
20385


In [199]:
df['drv_height_isnull'] = [1 if num == -1 else 0 for num in df['drv_height']]

print(sum(df['drv_height_isnull']))

20385


In [200]:
#drv_weight

print(df['drv_weight'].isnull().sum())
print(sum(df['drv_weight'] == -1))

0
50726


In [201]:
df['drv_weight_isnull'] = [1 if num == -1 else 0 for num in df['drv_weight']]

print(sum(df['drv_weight_isnull']))

50726


In [202]:
# drv_crash

print(df['drv_crash'].isnull().sum())
print(sum(df['drv_crash'] == -1))

0
15605


In [203]:
df['drv_crash_isnull'] = [1 if num == -1 else 0 for num in df['drv_crash']]

print(sum(df['drv_crash_isnull']))

15605


In [204]:
# drv_pts

print(df['drv_pts'].isnull().sum())
print(sum(df['drv_pts'] == -1))

0
3253


In [205]:
df['drv_pts_isnull'] = [1 if num == -1 else 0 for num in df['drv_pts']]
print(sum(df['drv_pts_isnull']))

3253


In [206]:
# drv_dui

print(df['drv_dui'].isnull().sum())
print(sum(df['drv_dui'] == -1))

0
3253


In [207]:
df['drv_dui_isnull'] = [1 if num == -1 else 0 for num in df['drv_dui']]
print(sum(df['drv_dui_isnull']))

3253


In [210]:
# drv_spd

print(df['drv_spd'].isnull().sum())
print(sum(df['drv_spd'] == -1))

0
3253


In [209]:
df['drv_spd_isnull'] = [1 if num == -1 else 0 for num in df['drv_spd']]

print(sum(df['drv_spd_isnull']))

3253


In [211]:
#veh_speed

print(df['veh_speed'].isnull().sum())
print(sum(df['veh_speed'] == -1))

0
88909


In [212]:
df['veh_speed_isnull'] = [1 if num == -1 else 0 for num in df['veh_speed']]
print(sum(df['veh_speed_isnull']))

88909


In [12]:
# df.head()

In [214]:
df.shape

(145063, 117)

In [13]:
# df.T

In [217]:
df.to_pickle('pp_train_isnull_1.pkl')

In [14]:
#calculate missing value counts for categorical features
# pd.set_option('display.max_rows', 120)


# df.isnull().sum()

In [15]:
# df.select_dtypes(include = ['object']).isnull().sum()

In [221]:
df['veh_type'].value_counts(dropna = False)

Truck            75713
Passenger Car    54805
Motorcycle       11247
NaN               3298
Name: veh_type, dtype: int64

In [222]:
# fill missing values(NANs) for categorical features
# veh_type

df['veh_type'].fillna('unknown', inplace = True)

In [224]:
print(df['veh_type'].isnull().sum())
print(df['veh_type'].value_counts(dropna = False))

0
Truck            75713
Passenger Car    54805
Motorcycle       11247
unknown           3298
Name: veh_type, dtype: int64


In [16]:
#veh_style

# df['veh_style'].fillna('unknown', inplace = True)

# print(df['veh_style'].isnull().sum())
# print(df['veh_style'].value_counts(dropna = False))

In [226]:
# veh_weight

df['veh_weight'].fillna('unknown', inplace = True)

print(df['veh_weight'].isnull().sum())
print(df['veh_weight'].value_counts())

0
unknown       133408
over 12T        9064
up to 12T       2484
up to 4.5T       107
Name: veh_weight, dtype: int64


In [17]:
# veh_manu

# df['veh_manu'].fillna('unknown', inplace = True)

# print(df['veh_manu'].isnull().sum())
# print(df['veh_manu'].value_counts(dropna = False))

In [228]:
# drv_status

df['drv_status'].fillna('unknown', inplace = True)

print(df['drv_status'].isnull().sum())
print(df['drv_status'].value_counts(dropna = False))

0
Clean         122547
Penalised      10318
No licence      8331
unknown         1994
Expired         1873
Name: drv_status, dtype: int64


In [18]:
# df.select_dtypes(include = ['object']).isnull().sum()

In [230]:
df.to_pickle('pp_train_isnull_2.pkl')

In [19]:
# do feature engineering

# df.T

In [233]:
#inc_datetime

df['inc_datetime_yr'] = df['inc_datetime'].dt.year

In [234]:
df.to_pickle('pp_train_isnull_3.pkl')

In [236]:
#new feature: veh_age = inc_datetime_yr - veh_+year

df['veh_age'] = df['inc_datetime_yr'] - df['veh_year']

In [245]:
#new feature_1: drv_ban1 = (inc_datetime_yr-drv_ban1_yr)*12+(inc_datetime_mon-drv_ban1_mo)
#new feature_2: dfv_ban2 = (inc_datetime_yr-drv_ban2_yr)*12+(inc_datetime_mon-drv_ban2_mo)

df['drv_ban1_num'] = (df['inc_datetime_yr']-df['drv_ban1_yr_num'])*12+(df['inc_datetime_mon']-df['drv_ban1_mo_num'])
df['drv_ban2_num'] = (df['inc_datetime_yr']-df['drv_ban2_yr_num'])*12+(df['inc_datetime_mon']-df['drv_ban2_mo_num'])

In [20]:
# (df['inc_datetime_yr']-df['drv_ban1_yr_num'])*12+(df['inc_datetime_mon']-df['drv_ban1_mo_num'])

In [21]:
# (df['inc_datetime_yr']-df['drv_ban2_yr_num'])*12+(df['inc_datetime_mon']-df['drv_ban2_mo_num'])

In [22]:
# df['drv_ban1_yr_num'].value_counts(dropna = False)

In [246]:
df.to_pickle('pp_train_isnull_4.pkl')

In [23]:
# df = pd.read_pickle('pp_train_isnull_4.pkl')
# df.head()

In [24]:
# df.T

In [25]:
# df.T

In [26]:
# df.info()

In [27]:
# pd.set_option('display.max_rows', 200)

# df.dtypes

In [9]:
df.drop(['inc_datetime', 'drv_ban1_mo', 'drv_ban1_yr', 'drv_ban2_mo', 'drv_ban2_yr'], axis = 1, inplace = True)

In [28]:
# df.T

In [11]:
df.drop(['veh_year'], axis = 1, inplace = True)

In [29]:
# df.select_dtypes(include = ['object']).T

In [30]:
# encoding = {'Unharmed': 0, 'Possible': 1, 'Minor': 2, 'Major': 3, 'Fatal': 4}

# y = df['injury'].map(encoding)
# print(y)

In [14]:
df.drop(['injury'], axis = 1, inplace = True)

In [31]:
# df.T

In [32]:
# X = pd.get_dummies(df)
# X.head()

In [33]:
# X.T

In [18]:
from sklearn.model_selection import GroupKFold

folds_split = list(GroupKFold(n_splits = 5).split(X,
                                                 groups = X.loc[:, 'incident_id']))

In [19]:
folds_split

[(array([     0,      1,      5, ..., 145060, 145061, 145062]),
  array([     2,      3,      4, ..., 145048, 145049, 145059])),
 (array([     0,      1,      2, ..., 145060, 145061, 145062]),
  array([    16,     17,     46, ..., 145056, 145057, 145058])),
 (array([     0,      1,      2, ..., 145058, 145059, 145060]),
  array([     7,      8,      9, ..., 145055, 145061, 145062])),
 (array([     2,      3,      4, ..., 145060, 145061, 145062]),
  array([     0,      1,      5, ..., 145034, 145035, 145036])),
 (array([     0,      1,      2, ..., 145059, 145061, 145062]),
  array([    30,     32,     33, ..., 145051, 145052, 145060]))]

In [20]:
folds_split[0]

(array([     0,      1,      5, ..., 145060, 145061, 145062]),
 array([     2,      3,      4, ..., 145048, 145049, 145059]))

In [21]:
folds_split[0][0]

array([     0,      1,      5, ..., 145060, 145061, 145062])

In [22]:
#further drop index columns: row_id, incident_id, vehicle_id, occupant_id

X.drop(['row_id', 'incident_id', 'vehicle_id', 'occupant_id'], axis = 1, inplace = True)

In [23]:
X.shape

(145063, 357)

In [24]:
import lightgbm as lgb

lgb_data = lgb.Dataset(X, label = y)

In [22]:
params_1 = {'num_leaves': 54,
           'min_data_in_leaf': 79,
           'objective': 'multiclass',
           'num_class': 5,
           'metric': 'multi_logloss',
           'max_depth': -1,
           'learning_rate': 0.01,
           'boosting': 'gbdt',
           'feature_fraction': 0.9,
         'bagging_fraction': 0.8,
         'bagging_freq': 5,
         'verbosity': 200,
           'reg_alpha': 1.13,
           'reg_lambda': 0.36}

In [278]:
mod_1 = lgb.cv(params = params_1,
              num_boost_round = 2000,
              verbose_eval = 200,
              train_set = lgb_data,
              early_stopping_rounds = 100,
              folds = folds_split)

[200]	cv_agg's multi_logloss: 1.00118 + 0.00535021
[400]	cv_agg's multi_logloss: 0.920033 + 0.00682481
[600]	cv_agg's multi_logloss: 0.8957 + 0.00707179
[800]	cv_agg's multi_logloss: 0.884286 + 0.00712488
[1000]	cv_agg's multi_logloss: 0.877915 + 0.00722648
[1200]	cv_agg's multi_logloss: 0.873992 + 0.00728572
[1400]	cv_agg's multi_logloss: 0.871379 + 0.00743518
[1600]	cv_agg's multi_logloss: 0.869527 + 0.00738668
[1800]	cv_agg's multi_logloss: 0.86838 + 0.0074462
[2000]	cv_agg's multi_logloss: 0.867527 + 0.0073764


In [23]:
import xgboost as xgb

In [24]:
dtrain = xgb.DMatrix(data = X, label = y)

In [25]:
params_2 = {'objective': 'multi:softprob',
            'eval_metric': ['mlogloss'],
            'num_class': 5,
            'colsample_bytree': 0.6,
           'gamma': 0.5,
           'learning_rate': 0.05,
           'max_depth': 7,
            'min_child_weight': 5,
            'lambda': 0.5,
            'alpha': 0.5,
           'n_estimators': 500,
           'subsample': 0.6}

In [26]:
mod2 = xgb.cv(params = params_2,
             dtrain = dtrain,
             num_boost_round = 300,
             early_stopping_rounds = 100,
             verbose_eval = 200,
             folds = folds_split)

[0]	train-mlogloss:1.56385+0.000358841	test-mlogloss:1.56442+0.000261794
[200]	train-mlogloss:0.79818+0.00154134	test-mlogloss:0.883665+0.00725878
[299]	train-mlogloss:0.752278+0.00151103	test-mlogloss:0.874351+0.00717486
